/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fenghun_openglesdroid_jni_MyOpenglES */

#ifndef _Included_com_fenghun_openglesdroid_jni_MyOpenglES
#define _Included_com_fenghun_openglesdroid_jni_MyOpenglES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fenghun_openglesdroid_jni_MyOpenglES
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fenghun_openglesdroid_jni_MyOpenglES_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
